# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_label_placeholder.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 907)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_8.addWidget(self.checkBox_2)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_8.addWidget(self.checkBox_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_8.addWidget(self.checkBox_3)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_8.addWidget(self.checkBox)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_8.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_8.addWidget(self.checkBox_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_7.addWidget(self.spinBox)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../image/repouso_scaled.png"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.btn_repouso = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_repouso.setObjectName("btn_repouso")
        self.verticalLayout_9.addWidget(self.btn_repouso)
        self.status_repouso = QtWidgets.QFrame(self.groupBox_3)
        self.status_repouso.setMinimumSize(QtCore.QSize(0, 10))
        self.status_repouso.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.status_repouso.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_repouso.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_repouso.setObjectName("status_repouso")
        self.verticalLayout_9.addWidget(self.status_repouso)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../image/repouso1_scaled.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_13.addWidget(self.label_4)
        self.btn_abrir = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_abrir.setObjectName("btn_abrir")
        self.verticalLayout_13.addWidget(self.btn_abrir)
        self.status_abrir = QtWidgets.QFrame(self.groupBox_3)
        self.status_abrir.setMinimumSize(QtCore.QSize(0, 10))
        self.status_abrir.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.status_abrir.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_abrir.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_abrir.setObjectName("status_abrir")
        self.verticalLayout_13.addWidget(self.status_abrir)
        self.horizontalLayout_13.addLayout(self.verticalLayout_13)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../image/fechar_scaled.png"))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.btn_fechar = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_fechar.setObjectName("btn_fechar")
        self.verticalLayout_10.addWidget(self.btn_fechar)
        self.status_fechar = QtWidgets.QFrame(self.groupBox_3)
        self.status_fechar.setMinimumSize(QtCore.QSize(0, 10))
        self.status_fechar.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.status_fechar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_fechar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_fechar.setObjectName("status_fechar")
        self.verticalLayout_10.addWidget(self.status_fechar)
        self.horizontalLayout_13.addLayout(self.verticalLayout_10)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../image/extensao_scaled.png"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_14.addWidget(self.label_7)
        self.btn_extensao = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_extensao.setObjectName("btn_extensao")
        self.verticalLayout_14.addWidget(self.btn_extensao)
        self.status_extensao = QtWidgets.QFrame(self.groupBox_3)
        self.status_extensao.setMinimumSize(QtCore.QSize(0, 10))
        self.status_extensao.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.status_extensao.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_extensao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_extensao.setObjectName("status_extensao")
        self.verticalLayout_14.addWidget(self.status_extensao)
        self.horizontalLayout_13.addLayout(self.verticalLayout_14)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../image/flexao_scaled.png"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_12.addWidget(self.label_10)
        self.btn_flexao = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_flexao.setObjectName("btn_flexao")
        self.verticalLayout_12.addWidget(self.btn_flexao)
        self.status_flexao = QtWidgets.QFrame(self.groupBox_3)
        self.status_flexao.setMinimumSize(QtCore.QSize(0, 10))
        self.status_flexao.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.status_flexao.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_flexao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_flexao.setObjectName("status_flexao")
        self.verticalLayout_12.addWidget(self.status_flexao)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../image/supinacao_scaled.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.btn_supinacao = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_supinacao.setObjectName("btn_supinacao")
        self.verticalLayout_5.addWidget(self.btn_supinacao)
        self.status_supinacao = QtWidgets.QFrame(self.groupBox_3)
        self.status_supinacao.setMinimumSize(QtCore.QSize(0, 10))
        self.status_supinacao.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.status_supinacao.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_supinacao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_supinacao.setObjectName("status_supinacao")
        self.verticalLayout_5.addWidget(self.status_supinacao)
        self.horizontalLayout_13.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../image/pronacao_scaled.png"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.btn_pronacao = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_pronacao.setObjectName("btn_pronacao")
        self.verticalLayout_6.addWidget(self.btn_pronacao)
        self.status_pronacao = QtWidgets.QFrame(self.groupBox_3)
        self.status_pronacao.setMinimumSize(QtCore.QSize(0, 10))
        self.status_pronacao.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.status_pronacao.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_pronacao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_pronacao.setObjectName("status_pronacao")
        self.verticalLayout_6.addWidget(self.status_pronacao)
        self.horizontalLayout_13.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 250))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.GraphLayoutPlaceholder = QtWidgets.QVBoxLayout()
        self.GraphLayoutPlaceholder.setObjectName("GraphLayoutPlaceholder")
        self.verticalLayout_11.addLayout(self.GraphLayoutPlaceholder)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuEditar = QtWidgets.QMenu(self.menubar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuSobre = QtWidgets.QMenu(self.menubar)
        self.menuSobre.setObjectName("menuSobre")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionAbrir_game = QtWidgets.QAction(MainWindow)
        self.actionAbrir_game.setObjectName("actionAbrir_game")
        self.menuArquivo.addAction(self.actionSair)
        self.menuEditar.addAction(self.actionAbrir_game)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EMGsvm"))
        self.groupBox.setTitle(_translate("MainWindow", "Treino"))
        self.label_2.setText(_translate("MainWindow", "Movimentos"))
        self.checkBox_2.setText(_translate("MainWindow", "Supinação"))
        self.checkBox_4.setText(_translate("MainWindow", "Pronação"))
        self.checkBox_3.setText(_translate("MainWindow", "Flexão"))
        self.checkBox.setText(_translate("MainWindow", "Extensão"))
        self.checkBox_5.setText(_translate("MainWindow", "Abrir"))
        self.checkBox_6.setText(_translate("MainWindow", "Fechar"))
        self.label.setText(_translate("MainWindow", "Rodadas"))
        self.pushButton_3.setText(_translate("MainWindow", "Iniciar treino"))
        self.pushButton_2.setText(_translate("MainWindow", "Finalizar treino"))
        self.pushButton.setText(_translate("MainWindow", "Iniciar exercício"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Posição"))
        self.btn_repouso.setText(_translate("MainWindow", "REPOUSO"))
        self.btn_abrir.setText(_translate("MainWindow", "ABRIR"))
        self.btn_fechar.setText(_translate("MainWindow", "FECHAR"))
        self.btn_extensao.setText(_translate("MainWindow", "EXTENSÃO"))
        self.btn_flexao.setText(_translate("MainWindow", "FLEXÃO"))
        self.btn_supinacao.setText(_translate("MainWindow", "SUPINAÇÃO"))
        self.btn_pronacao.setText(_translate("MainWindow", "PRONAÇÃO"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Sinal"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuEditar.setTitle(_translate("MainWindow", "Editar"))
        self.menuSobre.setTitle(_translate("MainWindow", "Sobre"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionAbrir_game.setText(_translate("MainWindow", "Abrir jogo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

